package Enums;

public enum ReturnMessage {
    UNKNOWN_COMMAND,
    NO_LOCKED_ROOMS,
    ROOM_LOCKED,
    ROOM_DARK,
    NO_ROOM_THIS_DIRECTION,
    NO_ITEM_INVENTORY,
    NO_ITEM_ROOM,
    OK,
    NOT_A_DIRECTION,
    ITEM_NOT_FOOD,
    ITEM_NOT_WEAPON,
    ATTACK_UNSUCCESSFUL,
    WEAPON_OUT_OF_AMMO,
    ENEMY_DEFEATED, NO_WEAPON_EQUIPPED
}
